export interface Stone {
  slug: string;
  name: string;
  category: 'makrana-pure-white' | 'albeta' | 'dungri' | 'premium-granite' | 'home-temples' | 'premium-tiles' | 'bathroom-vanities' | 'handicraft-marble-art';
  categoryLabel: string;
  origin: string;
  description: string;
  story: string;
  color: string;
  colorHex: string;
  finishes: string[];
  applications: string[];
  density: string;
  porosity: string;
  images: string[];
}

export const STONES: Stone[] = [
  {
    slug: "makrana-pure-white",
    name: "Makrana Pure White",
    category: "makrana-pure-white",
    categoryLabel: "Makrana pure white",
    origin: "Makrana, Rajasthan",
    description: "The pristine white marble of the Taj Mahal. Sourced from the oldest quarries, it features unparalleled calcium purity and a crystalline structure that reflects light deeply.",
    story: "Extracted from the historic quarries of Makrana, this stone has stood as the hallmark of imperial architecture for centuries. Its white luster develops a unique glow over generations, making it an heirloom surface.",
    color: "Pure Crystalline White",
    colorHex: "#F2F3F4",
    finishes: ["Polished", "Honed", "Velvet"],
    applications: ["Flooring", "Bathrooms", "Pooja Rooms", "Feature Walls"],
    density: "2.73 g/cm³",
    porosity: "0.12%",
    images: ["/images/makrana_white_1.jpg", "/images/makrana_white_2.jpg", "/images/makrana_white_3.jpg"]
  },
  {
    slug: "makrana-albeta-premium",
    name: "Albeta Premium Marble",
    category: "albeta",
    categoryLabel: "Albeta",
    origin: "Makrana, Rajasthan",
    description: "A legendary variety characterized by its milky white background overlaid with soft grey veins and golden-brown highlights.",
    story: "Albeta marble is the connoisseur's choice. Each slab tells a quiet geologic story of Rajasthan, displaying structural integrity that allows it to be laid in grand book-matched layouts.",
    color: "Milky White with Gold/Grey Veining",
    colorHex: "#ECEAE4",
    finishes: ["Polished", "Honed"],
    applications: ["Flooring", "Countertops", "Staircases", "Wall Cladding"],
    density: "2.71 g/cm³",
    porosity: "0.15%",
    images: ["/images/albeta_1.jpg", "/images/albeta_2.jpg", "/images/albeta_3.jpg", "/images/albeta_4.jpg"]
  },
  {
    slug: "makrana-dungri-premium",
    name: "Dungri Premium Marble",
    category: "dungri",
    categoryLabel: "Dungri",
    origin: "Makrana, Rajasthan",
    description: "A highly durable and classical Makrana variety featuring a signature warm grey background patterned with cross-veining.",
    story: "Dungri is renowned for its resilience and historic popularity in traditional Indian courts. It brings a grounded, natural warmth to large flooring projects.",
    color: "Soft White-Grey with Distinct Dark Veins",
    colorHex: "#D5D7D8",
    finishes: ["Polished", "Honed"],
    applications: ["Flooring", "Pooja Rooms", "Cladding"],
    density: "2.72 g/cm³",
    porosity: "0.14%",
    images: ["/images/dungri_1.jpg", "/images/dungri_2.jpg"]
  },
  {
    slug: "black-taurus-granite",
    name: "Black Taurus Granite",
    category: "premium-granite",
    categoryLabel: "premium granite",
    origin: "Makrana, Rajasthan",
    description: "A deeply expressive slab where deep charcoal black is split by dramatic golden and ivory rivers.",
    story: "This quartzite-granite hybrid offers high resistance with maximum visual impact. It represents luxury with restraint — a commanding signature in modern kitchen installations.",
    color: "Deep Black with Intense Gold Streams",
    colorHex: "#1C1B19",
    finishes: ["Polished", "Satin", "Leathered"],
    applications: ["Kitchen Countertops", "Feature Walls", "Fireplace Surrounds"],
    density: "2.85 g/cm³",
    porosity: "0.05%",
    images: ["/images/granite_1.jpg", "/images/granite_2.jpg"]
  },
  {
    slug: "titanium-gold-granite",
    name: "Titanium Gold Granite",
    category: "premium-granite",
    categoryLabel: "premium granite",
    origin: "Makrana, Rajasthan",
    description: "A dramatic dark granite featuring deep black and charcoal hues interwoven with striking gold, ivory, and amber veining.",
    story: "Quarried in Makrana and finished in Jaipur, Titanium Gold is a statement of raw power. It is ideal for high-traffic custom fireplace surrounds, feature walls, and kitchen installations.",
    color: "Deep Obsidian Black with Golden Quartz Veins",
    colorHex: "#2B2620",
    finishes: ["Polished", "Leathered"],
    applications: ["Feature Walls", "Kitchen Countertops", "Bar Tops"],
    density: "2.90 g/cm³",
    porosity: "0.04%",
    images: ["/images/granite_3.jpg", "/images/granite_4.jpg"]
  },
  {
    slug: "desert-brown-granite",
    name: "Desert Brown Granite",
    category: "premium-granite",
    categoryLabel: "premium granite",
    origin: "Makrana, Rajasthan",
    description: "A balanced brown granite featuring a consistent grain structure of chocolate, black, and amber minerals.",
    story: "Desert Brown represents geological resilience. Its uniform density and consistent patterning make it the go-to selection for heavy-duty kitchen countertops and outdoor paving.",
    color: "Chocolate Brown with Black and Amber Grains",
    colorHex: "#5E4D40",
    finishes: ["Polished", "Leathered", "Honed"],
    applications: ["Flooring", "Facade Cladding", "Kitchen Countertops"],
    density: "2.75 g/cm³",
    porosity: "0.10%",
    images: ["/images/granite_brown_new.jpg"]
  },
  {
    slug: "lakha-red-granite",
    name: "Lakha Red Granite",
    category: "premium-granite",
    categoryLabel: "premium granite",
    origin: "Makrana, Rajasthan",
    description: "A rich, vibrant red granite with dark speckles and quartz highlights, highly valued for its durability.",
    story: "Lakha Red is Jaisalmer's iconic stone of luxury. Polished to a high luster in Jaipur, it is a favored choice for luxury accents, custom fireplaces, and outdoor staircases.",
    color: "Vibrant Imperial Red with Grey Clusters",
    colorHex: "#8B2B1B",
    finishes: ["Polished", "Lappato", "Honed"],
    applications: ["Flooring", "Cladding", "Bathroom Vanities"],
    density: "2.80 g/cm³",
    porosity: "0.08%",
    images: ["/images/granite_red_new.jpg"]
  },
  {
    slug: "platinum-white-granite",
    name: "Platinum White Granite",
    category: "premium-granite",
    categoryLabel: "premium granite",
    origin: "Makrana, Rajasthan",
    description: "A clean, white granite with fine black and charcoal speckles, providing a neutral and modern aesthetic.",
    story: "Platinum White is Jalore's contribution to modern minimal architecture. It offers a bright, light-reflective surface that maintains absolute resistance to high traffic and acidic staining.",
    color: "Pristine White with Charcoal Flecks",
    colorHex: "#E5E6E4",
    finishes: ["Polished", "Lappato", "Flamed"],
    applications: ["Flooring", "Facade Cladding", "Staircases"],
    density: "2.72 g/cm³",
    porosity: "0.12%",
    images: ["/images/granite_white_new.jpg"]
  },
  {
    slug: "makrana-white-home-temple",
    name: "Makrana White Home Temple",
    category: "home-temples",
    categoryLabel: "Home temples",
    origin: "Makrana, Rajasthan",
    description: "A hand-carved home mandir, intricately crafted by master artisans in pure Makrana white marble, featuring traditional jaali work.",
    story: "Carved from block marble selected for spiritual purity, this sanctuary features custom pillars and delicate lattice patterns that play beautifully with interior lighting.",
    color: "Pure Translucent White",
    colorHex: "#FFFFFF",
    finishes: ["Polished"],
    applications: ["Pooja Rooms", "Bespoke Artworks"],
    density: "2.73 g/cm³",
    porosity: "0.10%",
    images: ["/images/temple_4.jpg", "/images/temple_1.jpg", "/images/temple_2.jpg", "/images/temple_3.jpg"]
  },
  {
    slug: "premium-porcelain-slabs",
    name: "Premium Porcelain Slabs",
    category: "premium-tiles",
    categoryLabel: "premium tiles",
    origin: "Makrana, Rajasthan",
    description: "Ultra-large format porcelain panels in refined slate grey, warm sand, and sage green, offering seamless surfacing solutions.",
    story: "Manufactured in Rajasthan, these high-performance porcelain panels represent the pinnacle of modern architectural surfacing. They are lightweight, non-porous, and perfect for creating continuous, grout-free wall claddings and kitchen countertops.",
    color: "Sage Green, Slate Grey & Warm Sand",
    colorHex: "#C2C6A9",
    finishes: ["Satin Matt", "Polished"],
    applications: ["Flooring", "Facade Cladding", "Kitchen Countertops", "Shower Walls"],
    density: "2.40 g/cm³",
    porosity: "0.01%",
    images: ["/images/tiles_2.jpg", "/images/tiles_1.jpg", "/images/tiles_3.jpg", "/images/tiles_4.jpg"]
  },
  {
    slug: "nero-marquina-gold-vanity",
    name: "Nero Marquina Gold Vanity",
    category: "bathroom-vanities",
    categoryLabel: "Bathroom Vanities",
    origin: "Makrana, Rajasthan",
    description: "A stunning bespoke bathroom vanity featuring premium Nero Marquina-style black marble with bold gold veining, a modern integrated design, and an elegant circular mirror setup.",
    story: "Designed to create a bold, high-contrast statement in luxury washrooms. The rich black marble with striking gold veins is perfectly complemented by a modern black-and-white diamond tiled backsplash.",
    color: "Deep Black with Rich Gold Veins",
    colorHex: "#1A1A1A",
    finishes: ["Polished", "Satin"],
    applications: ["Bathroom Vanities", "Powder Rooms"],
    density: "2.69 g/cm³",
    porosity: "0.15%",
    images: ["/images/vanity_1.jpg"]
  },
  {
    slug: "bianco-lasa-gold-vanity",
    name: "Bianco Lasa Gold Vanity",
    category: "bathroom-vanities",
    categoryLabel: "Bathroom Vanities",
    origin: "Makrana, Rajasthan",
    description: "A luxurious washbasin vanity featuring warm gold-veined light stone, a brushed gold luxury faucet, and a clean geometric tiled backsplash.",
    story: "A perfect blend of minimalist shape and warm material textures. The soft, flowing gold-grey veins of the stone carcass create an inviting, serene atmosphere in contemporary bathrooms.",
    color: "Warm White with Flowing Gold and Grey Veining",
    colorHex: "#F0EDE6",
    finishes: ["Honed", "Polished"],
    applications: ["Bathroom Vanities", "Powder Rooms"],
    density: "2.70 g/cm³",
    porosity: "0.12%",
    images: ["/images/vanity_2.jpg"]
  },
  {
    slug: "choco-gold-ribbed-vanity",
    name: "Choco Gold Ribbed Vanity",
    category: "bathroom-vanities",
    categoryLabel: "Bathroom Vanities",
    origin: "Makrana, Rajasthan",
    description: "An avant-garde vanity crafted from dark textured marble, paired with an elegant rose gold/bronze faucet and a vertical ribbed ceramic tile backsplash.",
    story: "Created for sophisticated powder rooms. The dark, organic texture of the marble vanity is highlighted by the vertical linework of the warm clay-toned backsplash and a round minimalist mirror.",
    color: "Dark Chocolate with Warm Earthy Textures",
    colorHex: "#2B2523",
    finishes: ["Textured", "Honed"],
    applications: ["Bathroom Vanities", "Powder Rooms"],
    density: "2.68 g/cm³",
    porosity: "0.18%",
    images: ["/images/vanity_3.jpg"]
  },
  {
    slug: "shiva-kailash-plaque",
    name: "Shiva Kailash Relief Plaque",
    category: "handicraft-marble-art",
    categoryLabel: "Handicraft and marble art",
    origin: "Makrana, Rajasthan",
    description: "An intricately hand-carved relief plaque in pure Makrana white marble, depicting Lord Shiva meditating on Mount Kailash.",
    story: "Created by master carvers in Jaipur to mark Mahashivratri. The delicate relief detailing captures the serene form of Shiva amidst stylized Himalayan peaks and desert sands.",
    color: "Pure White with Gold Highlights",
    colorHex: "#FFFFFF",
    finishes: ["Polished"],
    applications: ["Wall Art", "Home Mandirs", "Pooja Rooms"],
    density: "2.73 g/cm³",
    porosity: "0.10%",
    images: ["/images/handicraft_shiva_1.jpg"]
  },
  {
    slug: "sacred-linga-frame",
    name: "Sacred Linga Relief Frame",
    category: "handicraft-marble-art",
    categoryLabel: "Handicraft and marble art",
    origin: "Makrana, Rajasthan",
    description: "A framed marble relief panel featuring a hand-sculpted Shiva Linga, Trishul, and lotus blossoms set against a textured sand background.",
    story: "This custom devotional frame is carved from a selected block of Makrana marble, bordered by a polished white frame. The contrasting sand-textured backdrop highlights the smooth, sacred contours of the Linga.",
    color: "White Marble on Earthy Sand Texture",
    colorHex: "#ECE5DB",
    finishes: ["Polished", "Textured"],
    applications: ["Pooja Rooms", "Spiritual Decors"],
    density: "2.73 g/cm³",
    porosity: "0.10%",
    images: ["/images/handicraft_shiva_2.jpg"]
  },
  {
    slug: "painted-marble-plaques",
    name: "Painted Marble Plaques",
    category: "handicraft-marble-art",
    categoryLabel: "Handicraft and marble art",
    origin: "Makrana, Rajasthan",
    description: "Round decorative plaques crafted from pure Makrana white marble, hand-painted with traditional Rajasthani Bani Thani and peacock motifs.",
    story: "Hand-painted by miniature art masters in Jaipur, these round marble plates serve as exquisite table accents or wall plaques. They bring the royal, multi-colored heritage of Rajasthan's royal courts into modern spaces.",
    color: "Multi-color detailing on Pure White Marble",
    colorHex: "#FFFFFF",
    finishes: ["Polished", "Hand-Painted"],
    applications: ["Wall Plaques", "Decorative Plates", "Exquisite Gifts"],
    density: "2.73 g/cm³",
    porosity: "0.10%",
    images: ["/images/handicraft_painted_1.jpg", "/images/handicraft_painted_2.jpg"]
  },
  {
    slug: "designer-moroccan-tiles",
    name: "Designer Moroccan Tiles",
    category: "premium-tiles",
    categoryLabel: "premium tiles",
    origin: "Makrana, Rajasthan",
    description: "Intricately patterned designer ceramic and cement tiles featuring classic Mediterranean, Moroccan, and geometric motifs.",
    story: "Hand-finished in Jaipur, these designer tiles offer a striking blend of vintage aesthetics and modern durability. They are ideal for creating accents, backsplashes, and bespoke highlights in premium bathrooms and kitchens.",
    color: "Vibrant Mediterranean Blue, Warm Amber, & Earthy Terracotta",
    colorHex: "#355E8D",
    finishes: ["Satin Matt", "Glazed"],
    applications: ["Bathroom Walls", "Kitchen Backsplashes", "Feature Floors"],
    density: "2.35 g/cm³",
    porosity: "0.02%",
    images: ["/images/tiles_dec_1.jpg", "/images/tiles_dec_2.jpg", "/images/tiles_dec_3.jpg"]
  },
  {
    slug: "classic-patterned-tiles",
    name: "Classic Patterned Tiles",
    category: "premium-tiles",
    categoryLabel: "premium tiles",
    origin: "Makrana, Rajasthan",
    description: "A vibrant collection of traditional patterned tiles, combining antique yellow and rich cobalt blue motifs with modern earth-toned borders.",
    story: "Handcrafted in Rajasthan, these tiles revive legacy geometric patterns. Highly versatile and durable, they add instant warmth and character to entryways, patios, and custom framing accents.",
    color: "Earthy Yellow, Cobalt Blue & Ash Grey",
    colorHex: "#D5A848",
    finishes: ["Satin Matt"],
    applications: ["Flooring Accents", "Wall Borders", "Kitchen Splashes"],
    density: "2.38 g/cm³",
    porosity: "0.02%",
    images: ["/images/tiles_dec_8.jpg", "/images/tiles_dec_4.jpg", "/images/tiles_dec_5.jpg", "/images/tiles_dec_6.jpg", "/images/tiles_dec_7.jpg"]
  }
];

export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'makrana-pure-white', label: 'Makrana pure white' },
  { id: 'albeta', label: 'Albeta' },
  { id: 'dungri', label: 'Dungri' },
  { id: 'premium-granite', label: 'premium granite' },
  { id: 'home-temples', label: 'Home temples' },
  { id: 'premium-tiles', label: 'premium tiles' },
  { id: 'bathroom-vanities', label: 'Bathroom Vanities' },
  { id: 'handicraft-marble-art', label: 'Handicraft and marble art' }
];
